@extends('layout')

@section('title', 'List of islands')

@section('head')
    <style>
        aside{
            background-color : white
        }
        main img {
            margin: 20px 0;
        }
        .bold{
            font-weight: bold;
        }
    </style>
@endsection

@section('content')
    <h1>Species by island</h1>
    <div class="row">

        <aside class="col-xs-12 col-sm-12 col-md-12 col-lg-4 pull-right">

            <ul>
                @foreach ($islands as $i)
                    <li>
                        <a class="list-link list-link-{{ $i->id }}" href="{{ route('islands.show', $i->id) }}">
                            {{ $i->name }}
                        </a>
                        <div class="hidden">
                            @include('island.specieslist', ['species' => $i->species])
                        </div>
                    </li>
                @endforeach
            </ul>
        </aside>

        <main class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <img src="{{ asset('images/Carte-iles-med-750.jpg') }}" usemap="#image-map">

            <map name="image-map">
                @php
                    $coords = [
                        "388,186,414,200",
                        "131,240,142,224",
                        "195,199,251,164",
                        "181,186,191,169",
                        "307,122,325,153",
                        "522,255,582,234",
                        "654,260,708,230",
                        "514,172,583,231",
                        "388,243,407,224",
                        "299,194,335,149",
                        "358,193,417,224",
                        "350,143,324,121"
                    ];
                @endphp
                @foreach($islands as $i)
                    <area class="map-link"
                          alt="{{ $i->name }}"
                          title="{{ $i->name }}"
                          href="{{ route('islands.show', $i->id) }}"
                          coords="{{ $coords[$i->id - 1] }}"
                          shape="rect"
                          data-island-id="{{ $i->id }}">
                @endforeach
            </map>
        </main>
    </div>
@endsection

@section('scripts')
    <script>
        $(function(){
            $('a.list-link').click(function(e){
                $(this).toggleClass('bold').next().toggleClass('hidden');
                return false;
            });
            $('area.map-link').click(function(e){
                $(".list-link").removeClass('bold').next().addClass('hidden');
                islandId = $(this).data('island-id');
                $('.list-link-' + islandId).addClass('bold').next().removeClass('hidden');
                return false;
            });
        });
    </script>
@endsection